-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE SALES_DATE LIKE '%2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC